nodes = [
  { :hostname => 'vault1',     	:ip => '10.130.50.2'  },
  { :hostname => 'vault2',     	:ip => '10.130.50.3'  },
  { :hostname => 'cpm1',       	:ip => '10.130.50.5'  },
  { :hostname => 'cpm2',       	:ip => '10.130.50.6'  },
  { :hostname => 'pvwa1',      	:ip => '10.130.50.10' },
  { :hostname => 'pvwa2',      	:ip => '10.130.50.11' },
  { :hostname => 'psm1',      	:ip => '10.130.50.15' },
  { :hostname => 'psm2',     	 :ip => '10.130.50.16' },
  { :hostname => 'trusty',   	 :ip => '10.130.50.75' },
  { :hostname => 'centos7',  	 :ip => '10.130.50.76' },
  { :hostname => 'solaris11',	 :ip => '10.130.50.77' },
  { :hostname => 'win10',    	 :ip => '10.130.50.80' },
  { :hostname => 'win2016',  	 :ip => '10.130.50.81' },
  { :hostname => 'dns',      	 :ip => '8.8.8.8'      }, 
  { :hostname => 'host1',    	 :ip => '10.130.50.250'}, 
  { :hostname => 'host2',    	 :ip => '10.130.50.251'}
]

Vagrant.configure("2") do |config|

###############
### VAULT 1 ###
###############
  config.vm.define "vault1" do |cfg|
    cfg.vm.box = "mwrock/Windows2016"
    cfg.vm.hostname = "vault1"
    cfg.vm.communicator = "winrm"
    cfg.vm.network :public_network, bridge: [ "en0: Wi-Fi (AirPort)", "en1: Wi-Fi (AirPort)" ], ip: "10.130.50.2", dns: "8.8.8.8"
    config.vm.synced_folder "./private_software", "/private_software"
    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "vault1"
      vb.memory = 1250
      vb.cpus = 1
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end

#############
###  CPM 1 ##
#############
  config.vm.define "cpm1" do |cfg|
    cfg.vm.box = "mwrock/Windows2016"
    cfg.vm.hostname = "cpm1"
    cfg.vm.communicator = "winrm"
    cfg.vm.network :public_network, bridge: [ "en0: Wi-Fi (AirPort)", "en1: Wi-Fi (AirPort)" ], ip: "10.130.50.5", dns: "8.8.8.8"
    config.vm.synced_folder "./private_software", "/private_software"
    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "cpm1"
      vb.memory = 1250
      vb.cpus = 1
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end

#############
###  PVWA  ##
#############
  config.vm.define "pvwa1" do |cfg|
    cfg.vm.box = "mwrock/Windows2016"
    cfg.vm.hostname = "pvwa1"
    cfg.vm.communicator = "winrm"
    cfg.vm.network :public_network, bridge: [ "en0: Wi-Fi (AirPort)", "en1: Wi-Fi (AirPort)" ], ip: "10.130.50.10", dns: "8.8.8.8"
    config.vm.synced_folder "./private_software", "/private_software"
    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "pvwa1"
      vb.memory = 1250
      vb.cpus = 1
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end
################
###  PSM SSH  ##
################
  config.vm.define "psm4ssh" do |cfg|
    cfg.vm.box = "mwrock/Windows2016"
    cfg.vm.hostname = "psm4ssh"
    cfg.vm.communicator = "winrm"
    cfg.vm.network :public_network, bridge: [ "en0: Wi-Fi (AirPort)", "en1: Wi-Fi (AirPort)" ], ip: "10.130.50.10", dns: "8.8.8.8"
    config.vm.synced_folder "./private_software", "/private_software"
    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "psm4ssh"
      vb.memory = 1250
      vb.cpus = 1
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end

end